import React from 'react';
import Head from 'next/head';
import { GetServerSideProps } from 'next';
import dynamic from 'next/dynamic';
import {
  QueryClient,
  QueryClientProvider,
  useQuery,
} from '@tanstack/react-query';
import { getTodos } from '../utils/api';
import styles from '../styles/Home.module.css';

const Table = dynamic(() => import('../components/Table/Table'), {
  ssr: false,
});
const AddTodo = dynamic(() => import('../components/AddTodo/AddTodo'), {
  ssr: false,
});

interface TodoItem {
  id: number;
  item: string;
}

interface Props {
  status: string;
  todos: TodoItem[];
  username: string;
}

const queryClient = new QueryClient();

export const getServerSideProps: GetServerSideProps<Props> = async () => {
  const { status } = await fetch('http://localhost:8000/status').then((x) =>
    x.json()
  );
  const { username } = await fetch('http://localhost:8000/username').then((x) =>
    x.json()
  );
  const todos = await getTodos();
  return {
    props: {
      status: status,
      todos: todos ? todos : [],
      username: username,
    },
  };
};

interface HomeProps {
  initialTodos: TodoItem[];
}

function Home({ initialTodos }: HomeProps): JSX.Element {
  const { isLoading, isError, data, error } = useQuery(['todos'], getTodos, {
    initialData: initialTodos,
  });

  const handleGetTodos = () => {
    queryClient.invalidateQueries(['todos']);
  };

  let mainContent = <Table todos={data} handleGetTodos={handleGetTodos} />;
  if (isLoading) {
    mainContent = <span>Loading...</span>;
  }

  if (isError) {
    const errorMessage = (error as { message: string }).message;
    mainContent = <span>Error: {errorMessage}</span>;
  }
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href='https://nextjs.org'>Next.js!</a>
        </h1>
        <AddTodo handleGetTodos={handleGetTodos} />
        {mainContent}
      </main>
    </div>
  );
}

export default function HomeWrapper({
  status,
  todos,
  username,
}: Props): JSX.Element {
  return (
    <QueryClientProvider client={queryClient}>
      <div className={styles.container}>
        <Home initialTodos={todos} />
        <div>
          Status is: {status}, your username is: {username}
        </div>
      </div>
    </QueryClientProvider>
  );
}
