import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { GetServerSideProps } from 'next';

import Table from '../components/Table/Table';

interface Props {
  status: string;
  todos: string[];
  username: string;
}

export const getServerSideProps: GetServerSideProps<Props> = async () => {
  const { status } = await fetch('http://localhost:8000/status').then((x) =>
    x.json()
  );
  const { username } = await fetch('http://localhost:8000/username').then((x) =>
    x.json()
  );
  const todos = await fetch('http://localhost:8000/todos').then((x) =>
    x.json()
  );
  return {
    props: {
      status: status,
      todos: todos,
      username: username,
    },
  };
};

export default function Home({ status, todos, username }: Props): JSX.Element {
  const todoList = todos ? <Table todos={todos} /> : <h3>Loading....</h3>;
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href='https://nextjs.org'>Next.js!</a>
        </h1>
        {todoList}
        <div>
          Status is: {status}, your username is: {username}
        </div>
      </main>
    </div>
  );
}
